# Ejemplo de fichero, cambia la dirección por la que te toque en clase
network:
  ethernets:
    enp0s3:
      dhcp4: false
      addresses:
        - 10.1.1.22/24
      nameservers: 
        addresses:
        - 172.16.2.2
      routes:
        - to: default
          via: 10.1.1.1

